Repository Trys-Ketch/trys-ketch-client, pull requests merged in 2023-02, with the labels that each got.

#127 ✨Feat control sound volume
  src/app/configStore.js
  src/app/slices/ingameSlice.js
  src/app/slices/loginSlice.js
  src/app/slices/muteSlice.js
  src/app/slices/soundSlice.js
  src/app/slices/userSlice.js
  src/components/button/SettingButton.jsx
  src/components/common/LoginButton.jsx
  src/components/common/Range.jsx
  src/components/game/Drawing.jsx
  src/components/layout/BGM.jsx
  src/components/modal/SettingModal.jsx
Labels: 🚀feat

#131 Fix/feedback
  public/img/non_submit.png
  src/assets/images/explain1.png
  src/assets/images/explain2.png
  src/assets/images/explain3.png
  src/assets/images/explain4.png
  src/assets/images/logo-characters.svg
  src/assets/images/non_submit.png
  src/components/common/Button.jsx
  src/components/common/FlatButton.jsx
  src/components/game/Drawing.jsx
  src/components/gameResult/ImageResult.jsx
  src/pages/GameRoom.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/Practice.jsx
  src/shared/Router.jsx
Labels: 🚀feat, 🔨fix

#132 Feature/ingame
  src/components/game/CircleTimer.jsx
  src/components/game/Drawing.jsx
  src/components/room/Difficulty.jsx
  src/hooks/useTimer.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
Labels: 🚀feat

#139 ✨Feat mypage
  src/api/my.js
  src/assets/icons/logout-icon.svg
  src/assets/images/logo-characters.png
  src/assets/images/logo-characters.svg
  src/components/chat/MessageList.jsx
  src/components/common/Tab.jsx
  src/components/game/Drawing.jsx
  src/components/modal/AchievementModal.jsx
  src/components/modal/DescriptionModal.jsx
  src/components/modal/ModalContainer.jsx
  src/components/mypage/MyBadge.jsx
  src/components/mypage/MyImage.jsx
  src/components/room/Attendee.jsx
  src/hooks/useIntersect.jsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/Guest.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/styles/theme.js
Labels: ✨enhancement, 🚀feat

#136 :necktie: Submit when player is not Submitted
  src/components/painting/Paint.jsx
  src/hooks/useGameRoomStomp.jsx
  src/pages/GameRoom.jsx
Labels: 🔨fix

#140 ✨ Feat mypage
  src/assets/icons/lock-icon.svg
  src/components/mypage/EmptyMyImage.jsx
  src/components/mypage/MyBadge.jsx
  src/components/mypage/MyBadgeLock.jsx
  src/components/mypage/MyImage.jsx
  src/components/mypage/MyImageLock.jsx
  src/hooks/useEventSource.jsx
  src/pages/Lobby.jsx
  src/pages/MyPage.jsx
Labels: 🚀feat, 🔨fix

#146 ✨ Feat zoom in canvas
  .yarn/cache/dayjs-npm-1.11.7-d5cd5b2919-5003a7c1dd.zip
  .yarn/install-state.gz
  package.json
  src/assets/icons/download-icon-white.svg
  src/assets/images/sad-trysketch.svg
  src/assets/sounds/alarm_sound.wav
  src/assets/sounds/chat_sound.wav
  src/assets/sounds/click_pop_sound.wav
  src/assets/sounds/enter_sound.wav
  src/assets/sounds/main-bgm.mp3
  src/assets/sounds/ready_sound.wav
  src/components/button/QuitButton.jsx
  src/components/chat/ChatBox.jsx
  src/components/common/FlatButton.jsx
  src/components/common/Modal.jsx
  src/components/common/Tab.jsx
  src/components/gameResult/ImageResult.jsx
  src/components/layout/BGM.jsx
  src/components/modal/QuitRoomModal.jsx
  src/components/modal/SettingModal.jsx
  src/components/mypage/MyImage.jsx
  src/components/mypage/ZoomInCanvas.jsx
  src/components/room/EmptyRoomList.jsx
  src/hooks/useSound.jsx
  src/pages/GameRoom.jsx
  src/pages/MyPage.jsx
  src/pages/Practice.jsx
  src/utils/downloadImage.js
  yarn.lock
Labels: ✨enhancement, 🚀feat

#149 Feature/denoteuser
  .yarn/install-state.gz
  package-lock.json
  src/components/mute/MuteUser.jsx
  src/components/mypage/ZoomInCanvas.jsx
  src/components/webRTC/Audio.jsx
  src/components/webRTC/AudioCall.tsx
  src/hooks/useObserveSpeaking.jsx
Labels: ✨enhancement, 🚀feat

#150 💄Feat animation in modal
  src/components/common/Modal.jsx
  src/components/layout/Layout.jsx
  src/components/modal/GuideModal.jsx
  src/components/modal/ModalContainer.jsx
  src/components/mypage/MyImage.jsx
  src/components/mypage/ZoomInCanvas.jsx
  src/pages/Lobby.jsx
  src/pages/MyPage.jsx
Labels: 🚀feat

#151 Feature/mypage
  src/components/common/Button.jsx
  src/components/common/FlatButton.jsx
  src/components/room/Room.jsx
  src/pages/InGame.jsx
Labels: 🔨fix

#152 Feature/sound
  src/assets/sounds/alarm_sound.wav
  src/components/chat/ChatBox.jsx
  src/components/common/Button.jsx
  src/components/common/FlatButton.jsx
  src/components/common/IconButton.jsx
  src/components/game/GameBoard.jsx
  src/components/gameboard/CircleTimer.jsx
  src/components/gameboard/LeftDiv..jsx
  src/hooks/useSound.jsx
  src/hooks/useTimer.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
Labels: 🚀feat, ♻refactor

#154 💄Add font fallback
  src/pages/Guest.jsx
  src/styles/font.css
Labels: 🔨fix

#155 Fix/feedback
  src/components/modal/EditProfileModal.jsx
  src/pages/GameRoom.jsx
Labels: 🔨fix

#157 Refactor/constants
  src/components/chat/ChatBox.jsx
  src/components/chat/Message.jsx
  src/components/common/Modal.jsx
  src/components/game/GameBoard.jsx
  src/components/gameResult/KeywordImageResult.jsx
  src/components/gameboard/CircleTimer.jsx
  src/components/login/GoogleLoginBtn.jsx
  src/components/login/KakaoLoginBtn.jsx
  src/components/login/NaverLoginBtn.jsx
  src/components/modal/EditProfileModal.jsx
  src/components/modal/GameModeModal.jsx
  src/components/mypage/MyBadge.jsx
  src/components/mypage/ZoomInCanvas.jsx
  src/components/painting/Paint.jsx
  src/components/room/Attendee.jsx
  src/components/room/Difficulty.jsx
  src/components/room/ReadyStartButton.jsx
  src/components/room/SetTime.jsx
  src/components/toast/ToastBar.jsx
  src/components/webRTC/AudioCall.tsx
  src/helper/constants.js
  src/helper/motions.js
  src/hooks/useGameRoomStomp.jsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
  src/utils/gameRoomStompUtils.js
Labels: ♻refactor
