Repository Trys-Ketch/trys-ketch-client, pull requests merged in 2023-01, with the labels that each got.

#1 [feature] 카카오 로그인 추가
  .env.development
  .gitignore
  src/App.jsx
  src/api/auth.js
  src/api/core/axios.js
  src/assets/icons/kakao_login.svg
  src/components/login/KakaoLoginBtn.jsx
  src/index.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/shared/Router.jsx
  src/utils/cookie.js
Labels: 🚀feat

#2 [feature] 그림판 페이지 추가
  .eslintrc.js
  src/App.jsx
  src/pages/Paint.jsx
  src/utils/floodFill.js
Labels: 🚀feat

#3 🧑‍💻Create github actions workflows
  .github/workflows/deploy-prod.yml
  src/components/login/KakaoLoginBtn.jsx
Labels: ✨enhancement

#5 💄마크업 작업 완료
  .yarn/cache/styled-reset-npm-4.4.4-96ecd00cd8-f8329b5836.zip
  .yarn/install-state.gz
  package.json
  src/assets/icons/user.png
  src/components/chat/Message.jsx
  src/components/chat/MessageForm.jsx
  src/components/chat/MessageList.jsx
  src/components/common/Avatar.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/game/AttendeeList.jsx
  src/components/game/Room.jsx
  src/components/game/RoomList.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/user/EmptyCard.jsx
  src/components/user/UserCard.jsx
  src/index.jsx
  src/pages/GameRoom.jsx
  src/pages/Guest.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/MyPage.jsx
  src/shared/Router.jsx
  src/styles/GlobalStyle.js
  yarn.lock
Labels: 🚀feat

#7 Feature/guest room
  .yarn/cache/@reduxjs-toolkit-npm-1.9.1-d51a310268-e6700a0d45.zip
  .yarn/cache/immer-npm-9.0.17-7ff1f414fd-046d562b74.zip
  .yarn/cache/redux-persist-npm-6.0.0-56dad69feb-edaf10dbf1.zip
  .yarn/cache/redux-thunk-npm-2.4.2-3acdaaf7b0-c7f757f6c3.zip
  .yarn/cache/reselect-npm-4.1.7-c37108c640-738d8e2b8f.zip
  .yarn/install-state.gz
  package.json
  src/api/auth.js
  src/api/core/axios.js
  src/api/user.js
  src/app/configStore.js
  src/app/slices/loginSlice.js
  src/app/slices/userSlice.js
  src/components/login/KakaoLoginBtn.jsx
  src/index.jsx
  src/pages/Guest.jsx
  src/utils/cookie.js
  yarn.lock
Labels: 🚀feat

#16 ✨공통 컴포넌트 & 모달 컴포넌트 관리 & 로비 페이지 완성
  .eslintrc.js
  .pnp.cjs
  .yarn/cache/@loadable-babel-plugin-npm-5.13.2-b7650ded1a-c7e8376d97.zip
  .yarn/cache/@loadable-component-npm-5.15.2-9e852903c2-dd027f3f9f.zip
  .yarn/install-state.gz
  package.json
  src/app/configStore.js
  src/app/slices/modalSlice.js
  src/assets/icons/cancel-icon.svg
  src/assets/icons/mike-icon.svg
  src/assets/icons/mike-mute-icon.svg
  src/assets/icons/setting-icon.svg
  src/assets/icons/speaker-icon.svg
  src/assets/icons/speaker-mute-icon.svg
  src/components/button/MikeButton.jsx
  src/components/button/SettingButton.jsx
  src/components/chat/Message.jsx
  src/components/chat/MessageForm.jsx
  src/components/common/Button.jsx
  src/components/common/FlatButton.jsx
  src/components/common/IconButton.jsx
  src/components/common/Modal.jsx
  src/components/common/Range.jsx
  src/components/common/Switch.jsx
  src/components/common/TextInput.jsx
  src/components/game/Guessing.jsx
  src/components/game/MakeSentence.jsx
  src/components/layout/Container.jsx
  src/components/layout/FloatBox.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Panel.jsx
  src/components/login/KakaoLoginBtn.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/modal/InviteCodeModal.jsx
  src/components/modal/ModalContainer.jsx
  src/components/modal/SettingModal.jsx
  src/components/painting/Paint.jsx
  src/components/room/EmptyRoomList.jsx
  src/components/room/Pagination.jsx
  src/components/room/Room.jsx
  src/components/user/UserCard.jsx
  src/hooks/useModal.jsx
  src/pages/GameRoom.jsx
  src/pages/Guest.jsx
  src/pages/InGame.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/styles/theme.js
  yarn.lock
Labels: 🚀feat

#20 ✨채팅 기능 추가
  .eslintrc.js
  src/api/room.js
  src/api/user.js
  src/app/slices/userSlice.js
  src/components/chat/ChatBox.jsx
  src/components/chat/Message.jsx
  src/components/chat/MessageForm.jsx
  src/components/chat/MessageList.jsx
  src/components/common/Range.jsx
  src/components/common/Switch.jsx
  src/components/modal/SettingModal.jsx
  src/components/user/LobbyProfile.jsx
  src/pages/GameRoom.jsx
  src/pages/Lobby.jsx
  src/utils/types.js
Labels: 🚀feat

#39 🐛 언마운트시 sse 연결해제
  src/App.jsx
  src/components/common/Button.jsx
  src/components/room/AttendeeList.jsx
  src/pages/GameRoom.jsx
  src/pages/Lobby.jsx
Labels: 🔨fix

#40 Fix/media agree
  src/api/room.js
  src/components/room/Pagination.jsx
  src/components/webRTC/AudioCall.tsx
  src/pages/GameRoom.jsx
  src/pages/Lobby.jsx
Labels: 🐞bug, 🔨fix

#47 :lipstick: In Styling timer
  src/App.jsx
  src/components/game/Drawing.jsx
  src/components/game/Guessing.jsx
  src/components/game/MakeSentence.jsx
  src/components/painting/Paint.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
Labels: 🚀feat

#48 Fix/sse
  .env.development
  src/components/chat/Message.jsx
  src/components/common/Modal.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/modal/InviteCodeModal.jsx
  src/components/modal/QuitRoomModal.jsx
  src/components/room/Pagination.jsx
  src/pages/Lobby.jsx
Labels: ✨enhancement, 🔨fix

#51 Feat/sns login
  src/api/auth.js
  src/components/login/GoogleLoginBtn.jsx
  src/components/login/KakaoLoginBtn.jsx
  src/components/login/NaverLoginBtn.jsx
  src/components/room/Pagination.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/shared/Router.jsx
Labels: 🚀feat

#52 🩹 Fix simples
  src/components/login/GoogleLoginBtn.jsx
  src/components/login/NaverLoginBtn.jsx
Labels: 🔨fix

#54 ✨Feat Toast
  .eslintrc.js
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/@motionone-animation-npm-10.15.1-f581cc96f3-75b7a1e6c4.zip
  .yarn/cache/@motionone-dom-npm-10.15.5-4add8e8195-2453fe3df6.zip
  .yarn/cache/@motionone-easing-npm-10.15.1-793a4addaa-cf7cfcf991.zip
  .yarn/cache/@motionone-generators-npm-10.15.1-9b31cd017c-0eb6797a64.zip
  .yarn/cache/@motionone-types-npm-10.15.1-0bac46e291-98091f7dca.zip
  .yarn/cache/@motionone-utils-npm-10.15.1-13443b5c16-6ef13cd663.zip
  .yarn/cache/framer-motion-npm-8.5.2-b03b40f015-d58eabc825.zip
  .yarn/cache/hey-listen-npm-1.0.8-adb7dae9da-6bad60b367.zip
  .yarn/cache/nanoid-npm-4.0.0-924f5c6312-7d5946df5c.zip
  .yarn/cache/styled-reset-npm-4.4.5-bd729c3b44-3cd86e5d55.zip
  .yarn/install-state.gz
  package.json
  public/index.html
  src/assets/icons/cancel-toast-icon.svg
  src/assets/icons/check-toast-icon.svg
  src/assets/icons/info-toast-icon.svg
  src/components/chat/ChatBox.jsx
  src/components/common/Modal.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/modal/InviteCodeModal.jsx
  src/components/modal/SettingModal.jsx
  src/components/room/Pagination.jsx
  src/components/room/Room.jsx
  src/components/toast/ToastBar.jsx
  src/components/toast/ToastProvider.jsx
  src/components/toast/core/Toaster.js
  src/components/user/LobbyProfile.jsx
  src/index.jsx
  src/pages/GameRoom.jsx
  src/pages/Guest.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
  yarn.lock
Labels: 🚀feat

#59 ♻ Refactor gameroom socket
  src/components/modal/ModalContainer.jsx
  src/components/room/Attendee.jsx
  src/components/room/AttendeeList.jsx
  src/components/room/Explain.jsx
  src/components/room/Room.jsx
  src/components/toast/ToastBar.jsx
  src/components/user/LobbyProfile.jsx
  src/hooks/useDidMountEffect.jsx
  src/pages/GameRoom.jsx
Labels: ♻refactor

#61 Feature/ingame
  src/components/game/Drawing.jsx
  src/components/game/Guessing.jsx
  src/components/game/SubmittedPlayer.jsx
  src/components/gameResult/EmptyResultUser.jsx
  src/components/gameResult/ResultUser.jsx
  src/components/gameResult/ResultUserList.jsx
  src/components/painting/Paint.jsx
  src/hooks/useTimer.jsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
Labels: 🚀feat

#63 🍱 Update meta tags & favicon
  public/favicon.ico
  public/img/sanic.png
  public/img/sanic.webp
  public/img/trysketch.svg
  public/index.html
Labels: 🚀feat

#62 ✨Feat sound
  .yarn/cache/howler-npm-2.2.3-254b855819-c04ce19411.zip
  .yarn/install-state.gz
  package.json
  src/assets/icons/mic-icon.svg
  src/assets/icons/mic-mute-icon.svg
  src/assets/sound/alarm.wav
  src/assets/sound/main-bgm.mp3
  src/components/button/MicButton.jsx
  src/components/game/Drawing.jsx
  src/components/layout/BGM.jsx
  src/components/modal/SettingModal.jsx
  src/components/room/Attendee.jsx
  src/hooks/useSound.jsx
  src/hooks/useTimer.jsx
  src/pages/GameRoom.jsx
  src/shared/Router.jsx
  src/utils/turnOnSound.js
  yarn.lock
Labels: 🚀feat

#65 🩹 Fix simples
  .yarn/cache/react-ga-npm-3.3.1-de5c01fc6e-3026976d02.zip
  package.json
  public/img/trysketch.png
  public/img/trysketch.svg
  public/index.html
  src/components/layout/BGM.jsx
  src/utils/turnOnSound.js
  yarn.lock
Labels: 🔨fix

#66 🧐 Add GA basic code
  public/index.html
  src/components/layout/Layout.jsx
  src/ga/RouteChangeTraker.jsx
  src/index.jsx
Labels: 🚀feat

#68 👔 Add prevent refresh & go back
  .eslintrc.js
  public/index.html
  src/components/webRTC/AudioCall.tsx
  src/hooks/usePreventGoBack.jsx
  src/hooks/usePreventRefresh.jsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
  src/pages/Lobby.jsx
  src/shared/Router.jsx
Labels: 🚀feat

#70 ✨ Feat NotFound page
  src/assets/images/jumping-trysketch.svg
  src/pages/NotFound.jsx
  src/shared/Router.jsx
Labels: 🚀feat

#74 :sparkles: Feature local mute
  src/app/slices/muteSlice.js
  src/components/button/MicButton.jsx
  src/components/webRTC/AudioCall.tsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/InGame.jsx
Labels: 🚀feat

#75 🧐 Add GA button event
  src/components/chat/ChatBox.jsx
  src/components/common/LoginButton.jsx
  src/components/game/Drawing.jsx
  src/components/layout/Layout.jsx
  src/components/login/GoogleLoginBtn.jsx
  src/components/login/KakaoLoginBtn.jsx
  src/components/login/NaverLoginBtn.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/modal/InviteCodeModal.jsx
  src/components/modal/SettingModal.jsx
  src/components/painting/Paint.jsx
  src/components/room/Attendee.jsx
  src/components/room/Room.jsx
  src/ga/GAEventTrack.js
  src/ga/GAEventTypes.js
  src/ga/GARouteTracker.jsx
  src/pages/GameResult.jsx
  src/pages/GameRoom.jsx
  src/pages/Guest.jsx
  src/pages/InGame.jsx
  src/pages/Lobby.jsx
  src/pages/Login.jsx
Labels: 🚀feat

#79 Fix/sound
  src/hooks/useTimer.jsx
  src/pages/GameRoom.jsx
Labels: 🔨fix

#81 Fix/style
  src/components/gameResult/EmptyResultUser.jsx
  src/components/gameResult/ResultUserList.jsx
  src/pages/GameResult.jsx
Labels: 🔨fix

#83 :bug: Disable undo redo when submitted
  src/components/painting/Paint.jsx
Labels: 🔨fix

#89 Fix/style
  src/components/button/SettingButton.jsx
  src/components/common/LoginButton.jsx
  src/components/game/Drawing.jsx
  src/components/room/Attendee.jsx
  src/hooks/useTimer.jsx
  src/pages/GameResult.jsx
  src/pages/Lobby.jsx
Labels: 🔨fix

#90 Feature/ingame
  src/components/game/CircleTimer.jsx
  src/components/game/Round.jsx
  src/components/game/SubmittedPlayer.jsx
  src/pages/GameResult.jsx
  src/pages/InGame.jsx
Labels: ✨enhancement, 🔨fix

#92 :necktie: Reset Drawing state
  src/components/painting/Paint.jsx
  src/pages/GameRoom.jsx
Labels: 🔨fix

#93 Fix/sound
  src/api/my.js
  src/app/slices/modalSlice.js
  src/assets/icons/badge-icon.svg
  src/assets/icons/download-icon.svg
  src/assets/icons/empty-like-icon.svg
  src/assets/icons/like-icon.svg
  src/assets/icons/logout-icon.svg
  src/assets/icons/notice-icon.svg
  src/components/button/QuitButton.jsx
  src/components/button/RefreshButton.jsx
  src/components/button/SettingButton.jsx
  src/components/gameResult/ImageResult.jsx
  src/components/gameResult/KeywordResult.jsx
  src/components/modal/EditProfileModal.jsx
  src/components/modal/KickModal.jsx
  src/components/modal/ModalContainer.jsx
  src/components/room/Attendee.jsx
  src/components/user/MyProfile.jsx
  src/hooks/useTimer.jsx
  src/pages/GameResult.jsx
  src/pages/Guest.jsx
  src/pages/Lobby.jsx
  src/pages/MyPage.jsx
Labels: ✨enhancement, 🚀feat

#96 Feature/mypage
  .yarn/cache/file-saver-npm-2.0.5-2c3bc40d53-c62d96e5ce.zip
  .yarn/cache/react-ga-npm-3.3.1-de5c01fc6e-3026976d02.zip
  .yarn/cache/react-ga4-npm-2.0.0-95ba003d38-7cb9f2d786.zip
  .yarn/install-state.gz
  package.json
  src/api/my.js
  src/components/gameResult/ImageResult.jsx
  src/components/modal/EditProfileModal.jsx
  src/components/user/MyProfile.jsx
  src/components/webRTC/AudioCall.tsx
  src/ga/GAEventTrack.js
  src/ga/GARouteTracker.jsx
  src/hooks/usePreventGoBack.jsx
  src/index.jsx
  src/pages/GameResult.jsx
  src/pages/Lobby.jsx
  src/pages/MyPage.jsx
  yarn.lock
Labels: ✨enhancement, 🚀feat

#98 Hotfix
  src/components/gameResult/ImageResult.jsx
  src/components/modal/EditProfileModal.jsx
Labels: 🔨fix

#117 Fix/feedback
  src/assets/fonts/TTTogether.woff2
  src/components/gameResult/ImageResult.jsx
  src/components/modal/EditProfileModal.jsx
  src/components/modal/QuitRoomModal.jsx
  src/styles/font.css
Labels: ✨enhancement, 🔨fix

#123 Fix/feedback
  README.md
  src/assets/icons/user-body-icon.svg
  src/assets/icons/user-head-icon.svg
  src/assets/icons/user-icon.svg
  src/components/common/TextInput.jsx
  src/components/common/Tooltip.jsx
  src/components/game/Drawing.jsx
  src/components/game/SubmittedPlayer.jsx
  src/components/layout/Layout.jsx
  src/components/modal/CreateRoomModal.jsx
  src/components/modal/EditProfileModal.jsx
  src/components/painting/Paint.jsx
  src/components/webRTC/AudioCall.tsx
  src/pages/Lobby.jsx
  src/pages/MyPage.jsx
  src/shared/Router.jsx
Labels: ✨enhancement, 🚀feat
